# Generated by Django 2.1.15 on 2022-05-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prepay',
            fields=[
                ('prepay_id', models.CharField(auto_created=True, max_length=25, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=25)),
                ('prepay_amount', models.FloatField()),
                ('prepay_balance', models.FloatField()),
                ('account_id', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('prepay_id', models.CharField(max_length=25)),
                ('account_id', models.CharField(max_length=25)),
                ('project_name', models.CharField(max_length=64)),
                ('project_type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1024)),
                ('due_time', models.DateTimeField()),
                ('payment_per_task', models.FloatField()),
                ('project_status', models.IntegerField()),
                ('task_num', models.IntegerField()),
                ('completed_task_num', models.IntegerField()),
                ('project_star', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='project_id_pool',
            fields=[
                ('project_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reward_record',
            fields=[
                ('reward_id', models.CharField(auto_created=True, max_length=25, primary_key=True, serialize=False)),
                ('ta_id', models.CharField(max_length=25)),
                ('reward_amount', models.FloatField()),
                ('reward_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=25)),
                ('task_status', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('due_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Task_association',
            fields=[
                ('ta_id', models.CharField(auto_created=True, max_length=25, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=25)),
                ('task_id', models.CharField(max_length=25)),
                ('project_id', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Web_account',
            fields=[
                ('PAF_id', models.CharField(auto_created=True, max_length=25, primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=25)),
                ('PAF_type', models.CharField(max_length=4)),
                ('PAF_amount', models.FloatField()),
                ('PAF_balance', models.FloatField()),
                ('PAF_time', models.DateTimeField()),
            ],
        ),
    ]
