# Generated by Django 2.1.15 on 2022-05-23 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Total_account',
            new_name='Web_account',
        ),
        migrations.RemoveField(
            model_name='task',
            name='PAF_id',
        ),
    ]
