# Generated by Django 2.1.15 on 2022-06-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_account',
            name='PAF_type',
            field=models.CharField(max_length=10),
        ),
    ]
