# Generated by Django 2.1.15 on 2022-06-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_project_item_per_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_target',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
