# Generated by Django 2.1.15 on 2022-06-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0004_project_project_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
