# Generated by Django 2.1.15 on 2022-06-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0005_project_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=20)),
                ('error', models.CharField(max_length=60)),
                ('error_value', models.CharField(max_length=60)),
            ],
        ),
    ]
