# Generated by Django 2.1.15 on 2022-04-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_card',
            fields=[
                ('BC_id', models.CharField(auto_created=True, max_length=25, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=20)),
                ('card_num', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('account_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('account_type', models.IntegerField()),
                ('tel', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=2)),
                ('ID_num', models.CharField(max_length=25)),
                ('nickname', models.CharField(max_length=20)),
                ('mail_add', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
                ('level', models.IntegerField()),
                ('experience', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('account_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('account_type', models.IntegerField()),
                ('tel', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=2)),
                ('ID_num', models.CharField(max_length=25)),
                ('nickname', models.CharField(max_length=20)),
                ('mail_add', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User_id_pool',
            fields=[
                ('account_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('AB_id', models.CharField(auto_created=True, max_length=25, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=20)),
                ('account_num', models.FloatField()),
                ('payment_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet_record',
            fields=[
                ('cw_id', models.CharField(auto_created=True, max_length=25, primary_key=True, serialize=False)),
                ('AB_id', models.CharField(max_length=25)),
                ('cw_type', models.CharField(max_length=20)),
                ('cw_amount', models.FloatField()),
                ('pay_time', models.DateTimeField()),
            ],
        ),
    ]
