# Generated by Django 2.1.15 on 2022-04-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank_card',
            fields=[
                ('BC_id', models.CharField(auto_created=True, max_length=25, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=20)),
                ('card_num', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('account_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('account_type', models.IntegerField()),
                ('tel', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('avatar', models.ImageField(default='', upload_to='avatar/%Y/%m/%d')),
                ('gender', models.CharField(max_length=2)),
                ('ID_num', models.CharField(max_length=25)),
                ('nickname', models.CharField(max_length=20)),
                ('mail_add', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
                ('experience', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('account_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('account_type', models.IntegerField()),
                ('tel', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('avatar', models.ImageField(default='', upload_to='avatar/%Y/%m/%d')),
                ('gender', models.CharField(max_length=2)),
                ('ID_num', models.CharField(max_length=25)),
                ('nickname', models.CharField(max_length=20)),
                ('mail_add', models.CharField(max_length=20)),
                ('payment_password', models.CharField(max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('cw_id', models.CharField(auto_created=True, max_length=25, primary_key=True, serialize=False)),
                ('cw_type', models.CharField(max_length=4)),
                ('cw_amount', models.FloatField()),
                ('pay_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='user_id_pool',
            fields=[
                ('account_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('AB_id', models.CharField(auto_created=True, max_length=25, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=20)),
                ('account_num', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='AB_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.wallet'),
        ),
    ]
