# Generated by Django 2.1.15 on 2022-04-17 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_card',
            fields=[
                ('BC_id', models.CharField(auto_created=True, max_length=25, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=20)),
                ('card_num', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('cw_id', models.CharField(auto_created=True, max_length=25, primary_key=True, serialize=False)),
                ('cw_type', models.CharField(max_length=4)),
                ('cw_amount', models.FloatField()),
                ('pay_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('AB_id', models.CharField(auto_created=True, max_length=25, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=20)),
                ('account_num', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='AB_id',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='AB_id',
        ),
        migrations.AlterField(
            model_name='consumer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='record',
            name='AB_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.wallet'),
        ),
    ]
