# Generated by Django 2.1.15 on 2022-05-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0003_consumer_avatar_producer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
