# Generated by Django 4.0 on 2022-05-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_rename_total_account_web_account_remove_task_paf_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_star',
            field=models.FloatField(),
        ),
    ]
